name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub or GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set this secret in your GitHub repository settings
          password: ${{ secrets.DOCKER_PASSWORD }} # Set this secret in your GitHub repository settings

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .

      # Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
